### ISSUE TITLE
non-deterministic test: PhishingController should update list

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/controllers#896]
Test fails sometimes (only ever seen it in CI)

---
```
FAIL src/third-party/PhishingController.test.ts (21.51 s)
  ● PhishingController › should update lists

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      58 |   });
      59 | 
    > 60 |   it('should update lists', async () => {
         |   ^
      61 |     const controller = new PhishingController();
      62 |     controller.update({}, true);
      63 |     await controller.updatePhishingLists();

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/third-party/PhishingController.test.ts:60:3)
      at Object.<anonymous> (src/third-party/PhishingController.test.ts:9:1)
```
---
```
FAIL src/assets/CurrencyRateController.test.ts
  ● CurrencyRateController › should poll and update rate in the right interval

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      112 |     expect(fetchExchangeRateStub.calledTwice).toBe(false);
      113 |     await new Promise<void>((resolve) => setTimeout(() => resolve(), 150));
    > 114 |     expect(fetchExchangeRateStub.calledTwice).toBe(true);
          |                                               ^
      115 | 
      116 |     controller.destroy();
      117 |   });

      at src/assets/CurrencyRateController.test.ts:114:47
      at fulfilled (src/assets/CurrencyRateController.test.ts:5:58)
      at runNextTicks (node:internal/process/task_queues:61:5)
      at processTimers (node:internal/timers:499:9)

  ● CurrencyRateController › should poll correctly after being started, stopped, and started again

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      159 |     expect(fetchExchangeRateStub.calledThrice).toBe(false);
      160 |     await new Promise<void>((resolve) => setTimeout(() => resolve(), 150));
    > 161 |     expect(fetchExchangeRateStub.calledThrice).toBe(true);
          |                                                ^
      162 |   });
      163 | 
      164 |   it('should update exchange rate', async () => {

      at src/assets/CurrencyRateController.test.ts:161:48
      at fulfilled (src/assets/CurrencyRateController.test.ts:5:58)
```

**Comment by Gudahtt** [comment]
hey @BelfordZ , is this addressed by #897 ? I would not expect the phishing controller tests to timeout anymore.
